const assert = require("assert");
const { createOwnershipHistoryProvenanceDocumentSerializer, OwnershipHistoryProvenanceDocumentError } = require("../src/services/ownership-history-provenance-document-serializer.js");
function coverage(classification = "complete") { return { classification, targetKeys: ["1-1"], missingTargetKeys: [], uncertainTargetKeys: [] }; }
function evidence(serverId, sourceKind = "existing_generation", sourceDocumentIds = ["strategic-1"]) { return { schemaVersion: 1, proofVersion: 1, seasonId: "season-1", serverId, baseMapId: "season1-map", territoryCoverage: coverage(), structureCoverage: coverage("structurally_empty"), projectionRelationship: { classification: "complete", targetKeys: [], status: "matching_projection", differences: [] }, safetyDiagnosticCodes: ["z-code", "a-code"], sourceKind, sourceDocumentIds }; }
function context(overrides = {}) { return { seasonId: "season-1", baseMapId: "season1-map", activeSeasonId: "season-1", ...overrides }; }
function expectError(fn, code) { assert.throws(fn, (error) => error instanceof OwnershipHistoryProvenanceDocumentError && error.code === code); }
const serializer = createOwnershipHistoryProvenanceDocumentSerializer(); const recordA = evidence("server-366"); const recordB = evidence("server-367", "legacy_migration", ["legacy-b", "legacy-a"]); const document = serializer.serialize({ ...context(), records: [recordB, recordA] });
assert.strictEqual(document.documentId, "ownership-provenance:season-1:season1-map"); assert.deepStrictEqual(document.records.map((record) => record.serverId), ["server-366", "server-367"]); assert.deepStrictEqual(document.records[1].sourceDocumentIds, ["legacy-a", "legacy-b"]); assert.deepStrictEqual(document.records[0].safetyDiagnosticCodes, ["a-code", "z-code"]); const restored = serializer.deserialize(document, context()); assert.strictEqual(restored.status, "present"); assert.deepStrictEqual(restored.document, document);
assert.deepStrictEqual(serializer.deserialize(null, context()), { status: "unknown_provenance", seasonId: "season-1", baseMapId: "season1-map", records: [] }); const empty = serializer.serialize({ ...context(), records: [] }); assert.deepStrictEqual(serializer.deserialize(empty, context()).document.records, []); expectError(() => serializer.serialize({ ...context(), records: [recordA, { ...recordA, serverId: "server-366" }] }), "invalid_document"); expectError(() => serializer.serialize({ ...context(), records: [evidence("server-366", "first_run", ["source"])] }), "invalid_document"); expectError(() => serializer.deserialize({ ...empty, records: [recordA], seasonId: "season-2" }, context()), "scope_mismatch"); expectError(() => serializer.deserialize({ ...empty, schemaVersion: 2 }, context()), "invalid_document"); expectError(() => serializer.serialize({ ...context(), records: [{ ...recordA, trust: true }] }), "invalid_document"); expectError(() => serializer.serialize({ ...context(), sourceDocumentIds: [], records: [recordA] }), "invalid_document");
const firstInput = { ...context(), records: [recordB, recordA] }; const secondInput = { ...context(), records: [recordA, recordB] }; assert.deepStrictEqual(serializer.serialize(firstInput), serializer.serialize(secondInput)); const before = JSON.parse(JSON.stringify(firstInput)); const output = serializer.serialize(firstInput); output.records = undefined; assert.deepStrictEqual(firstInput, before); const restoredCopy = serializer.deserialize(document, context()); restoredCopy.document.records[0].serverId = "mutated"; assert.strictEqual(document.records[0].serverId, "server-366");
console.log("PASS provenance document round-trip, ordering, missing, empty, validation, and immutability scenarios"); console.log("1 test passed");