const assert = require("assert");
const fs = require("fs"); const path = require("path"); const vm = require("vm");
const { createOwnershipStartupCandidateGate } = require("../src/services/ownership-startup-candidate-gate.js");

const candidate = { provenanceState: {}, territoryRecords: [], structureRecords: [], targetCatalog: {}, persistedProjection: {} };
function gate(decisions) { const calls = []; return { calls, service: createOwnershipStartupCandidateGate({ createContextDecisionService: () => ({ decide(input) { calls.push(input); return decisions[input.serverId]; } }) }) }; }
function active(serverIds = ["server-366"]) { return { seasonId: "season-1", baseMapId: "season1-map", serverIds }; }
function assertDecision(result, expected) { assert.strictEqual(result.decision, expected); }

let context = gate({}); assertDecision(context.service.evaluate({ ...candidate, activeSeason: null }), "ready_setup"); assert.strictEqual(context.calls.length, 0);
context = gate({ "server-366": { decision: "ready" }, "server-367": { decision: "ready_empty" } }); assertDecision(context.service.evaluate({ ...candidate, activeSeason: active(["server-367", "server-366"]) }), "ready"); assert.deepStrictEqual(context.service.evaluate({ ...candidate, activeSeason: active(["server-367", "server-366"]) }).serverDecisions.map((entry) => entry.serverId), ["server-366", "server-367"]);
context = { calls: [], service: createOwnershipStartupCandidateGate({ createContextDecisionService: () => ({ decide(input) { context.calls.push(input); if (!input.provenanceState.present) return { decision: "recovery_required", reason: "missing_provenance" }; if (!input.persistedProjection.servers) return { decision: "recovery_required", reason: "missing_projection" }; if (input.seasonId !== "season-1" || input.baseMapId !== "season1-map") return { decision: "recovery_required", reason: "scope_mismatch" }; return { decision: "ready" }; } }) }) };
const contextFailure = context.service.evaluate({ ...candidate, provenanceState: {}, persistedProjection: {}, activeSeason: active(["server-366"]) }); assertDecision(contextFailure, "recovery_required"); assert.strictEqual(contextFailure.recoveryServers[0].reason, "missing_provenance"); assert.strictEqual(context.calls.length, 1);
const projectionFailure = context.service.evaluate({ ...candidate, provenanceState: { present: true }, persistedProjection: {}, activeSeason: active(["server-366"]) }); assert.strictEqual(projectionFailure.recoveryServers[0].reason, "missing_projection");
const scopeFailure = context.service.evaluate({ ...candidate, provenanceState: { present: true }, persistedProjection: { servers: [] }, activeSeason: { seasonId: "season-2", baseMapId: "other-map", serverIds: ["server-366"] } }); assert.strictEqual(scopeFailure.recoveryServers[0].reason, "scope_mismatch");
const isolated = gate({ "server-366": { decision: "ready" } }).service.evaluate({ ...candidate, territoryRecords: [{ seasonId: "season-2", serverId: "server-999" }], activeSeason: active(["server-366"]) }); assertDecision(isolated, "ready");
context = gate({ "server-366": { decision: "repair_eligible", repair: { differences: [{ territoryKey: "2-2" }] }, diagnostics: ["z", "a"] }, "server-367": { decision: "ready" } }); const repair = context.service.evaluate({ ...candidate, activeSeason: active(["server-367", "server-366"]) }); assertDecision(repair, "repair_required"); assert.deepStrictEqual(repair.repairServers.map((entry) => entry.serverId), ["server-366"]); assert.deepStrictEqual(repair.diagnostics, ["a", "z"]);
context = gate({ "server-366": { decision: "repair_eligible" }, "server-367": { decision: "recovery_required", reason: "uncertain_history", diagnostics: ["z", "a"] }, "server-368": { decision: "recovery_required", reason: "missing_provenance", diagnostics: ["b"] } }); const recovery = context.service.evaluate({ ...candidate, activeSeason: active(["server-368", "server-366", "server-367"]) }); assertDecision(recovery, "recovery_required"); assert.deepStrictEqual(recovery.recoveryServers.map((entry) => entry.serverId), ["server-367", "server-368"]); assert.deepStrictEqual(recovery.repairServers, []);
context = gate({ "server-366": { decision: "ready" }, "server-367": { decision: "ready_empty" } }); const before = JSON.stringify(candidate); context.service.evaluate({ ...candidate, activeSeason: active(["server-367", "server-366"]) }); assert.strictEqual(JSON.stringify(candidate), before); assert.strictEqual(context.calls.length, 2);
assert.throws(() => createOwnershipStartupCandidateGate({ createContextDecisionService: () => ({ decide() {} }), extra: true })); assert.throws(() => context.service.evaluate({ ...candidate, activeSeason: active(["server-366", "server-366"]) }));
const source = fs.readFileSync(path.join(__dirname, "..", "src", "services", "ownership-startup-candidate-gate.js"), "utf8"); const sandbox = { globalThis: {} }; vm.createContext(sandbox); vm.runInContext(source, sandbox); assert.strictEqual(typeof sandbox.globalThis.createOwnershipStartupCandidateGate, "function"); assert.ok(!/persistence|generation|audit|electron|ipc|fetch|score|fs|clock|startup|renderer/.test(source));
console.log("8 ownership startup candidate gate scenarios passed");