const assert = require("assert");
const fs = require("fs"); const path = require("path"); const vm = require("vm");
const { createOwnershipHistoryResolver } = require("../src/services/ownership-history-resolver.js");
const { createOwnershipProjectionComparator } = require("../src/services/ownership-projection-comparator.js");
const { createOwnershipHistoryCompletenessEvaluator } = require("../src/services/ownership-history-completeness-evaluator.js");
const { createOwnershipHistoryProvenanceEvidenceFactory } = require("../src/services/ownership-history-provenance-evidence-factory.js");
const { createOwnershipHistoryStartupDecisionService, OwnershipHistoryStartupDecisionServiceError } = require("../src/services/ownership-history-startup-decision-service.js");

const catalog = { territoryKeys: [{ row: 1, col: 1 }], structures: [{ structureId: "fort-1", footprint: [{ row: 1, col: 1 }] }] };
function territory(overrides = {}) { return { ownershipRecordId: "ownership-1", serverId: "server-366", seasonId: "season-1", territoryRef: { type: "normal_map_cell", row: 1, col: 1 }, ownerUnionId: "union-1", ownershipState: "owned", reviewState: "confirmed", effectiveAt: "2026-08-01T00:00:00Z", sourceType: "manual_entry", evidenceIds: [], actorId: "actor-1", reviewerId: "reviewer-1", reviewedAt: "2026-08-01T00:10:00Z", supersededBy: null, ...overrides }; }
function persisted(ownership = { "1-1": "union-1" }) { return { schemaVersion: 1, seasonId: "season-1", baseMapId: "season1-map", savedAt: "2026-08-01T00:00:00.000Z", servers: [{ id: "server-366", ownership }] }; }
function base(overrides = {}) { return { seasonId: "season-1", serverId: "server-366", baseMapId: "season1-map", territoryRecords: [territory()], structureRecords: [], targetCatalog: catalog, persistedProjection: persisted(), provenanceState: null, ...overrides }; }
function makeEvidence(input) { const factory = createOwnershipHistoryProvenanceEvidenceFactory({ createCompletenessEvaluator: (options) => createOwnershipHistoryCompletenessEvaluator({ ...options, ownershipHistoryResolver: createOwnershipHistoryResolver(options), ownershipProjectionComparator: createOwnershipProjectionComparator() }) }); return factory.createEvidence({ ...input, sourceKind: "existing_generation", sourceDocumentIds: ["strategic-1"] }); }
function service() { return createOwnershipHistoryStartupDecisionService({ createCompletenessEvaluator: (options) => createOwnershipHistoryCompletenessEvaluator({ ...options, ownershipHistoryResolver: createOwnershipHistoryResolver(options), ownershipProjectionComparator: createOwnershipProjectionComparator() }) }); }
function withEvidence(input, sourceKind = "existing_generation") { const factory = createOwnershipHistoryProvenanceEvidenceFactory({ createCompletenessEvaluator: (options) => createOwnershipHistoryCompletenessEvaluator({ ...options, ownershipHistoryResolver: createOwnershipHistoryResolver(options), ownershipProjectionComparator: createOwnershipProjectionComparator() }) }); const { provenanceState, ...factoryInput } = input; return { ...input, provenanceState: { status: "present", document: { documentId: "ownership-provenance:season-1:season1-map", documentType: "ownership-history-provenance", schemaVersion: 1, proofVersion: 1, seasonId: "season-1", baseMapId: "season1-map", records: [factory.createEvidence({ ...factoryInput, sourceKind, sourceDocumentIds: sourceKind === "first_run" ? [] : ["strategic-1"] })] } } }; }
function expectRecovery(result, reason) { assert.strictEqual(result.decision, "recovery_required"); if (reason) assert.strictEqual(result.reason, reason); }
const decision = service();
assert.deepStrictEqual(decision.decide(base({ provenanceState: { status: "unknown_provenance" } })).decision, "recovery_required");
const ready = decision.decide(withEvidence(base())); assert.strictEqual(ready.decision, "ready"); assert.strictEqual(ready.territoryCoverage.classification, "complete"); assert.strictEqual(ready.structureCoverage.classification, "structurally_empty");
const driftInput = base({ persistedProjection: persisted({}) }); assert.strictEqual(decision.decide(withEvidence(driftInput)).decision, "repair_eligible");
const firstRun = base({ territoryRecords: [], structureRecords: [], persistedProjection: persisted({}) }); assert.strictEqual(decision.decide(withEvidence(firstRun, "first_run")).decision, "ready_empty");
expectRecovery(decision.decide(base({ territoryRecords: [], structureRecords: [] }).constructor ? { ...base({ territoryRecords: [], structureRecords: [] }), provenanceState: { status: "present", document: { ...withEvidence(firstRun, "first_run").provenanceState.document, records: [] } } } : base()), "missing_server_provenance");
expectRecovery(decision.decide(withEvidence(base({ territoryRecords: [] }))), "projection_only");
expectRecovery(decision.decide(withEvidence(base({ territoryRecords: [territory({ ownershipState: "unknown", ownerUnionId: null })] }))), "uncertain_history");
const mismatch = withEvidence(base()); mismatch.provenanceState.document.records[0].territoryCoverage.classification = "partial"; expectRecovery(decision.decide(mismatch), "provenance_evidence_mismatch");
const otherContext = withEvidence(base({ serverId: "server-367", persistedProjection: { ...persisted(), servers: [{ id: "server-367", ownership: { "1-1": "union-1" } }] } })); expectRecovery(decision.decide(otherContext), "partial_history");
const permuted = withEvidence(base()); const again = withEvidence(base()); again.provenanceState.document.records.reverse(); assert.deepStrictEqual(decision.decide(permuted), decision.decide(again));
const before = JSON.stringify(permuted); decision.decide(permuted); assert.strictEqual(JSON.stringify(permuted), before);
expectRecovery(service().decide({ ...base(), provenanceState: { status: "present", document: {} } }), "malformed_provenance");
const source = fs.readFileSync(path.join(__dirname, "..", "src", "services", "ownership-history-startup-decision-service.js"), "utf8"); const sandbox = { globalThis: {} }; vm.createContext(sandbox); vm.runInContext(source, sandbox); assert.strictEqual(typeof sandbox.globalThis.createOwnershipHistoryStartupDecisionService, "function"); assert.ok(!/persistence|audit|electron|ipcRenderer|ipcMain|fetch|score|fs|clock/.test(source));
console.log("10 ownership startup decision scenarios passed");