const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { createOwnershipHistoryResolver } = require("../src/services/ownership-history-resolver.js");
const { createOwnershipProjectionComparator } = require("../src/services/ownership-projection-comparator.js");
const { createOwnershipHistoryCompletenessEvaluator } = require("../src/services/ownership-history-completeness-evaluator.js");
const { createOwnershipHistoryProvenanceEvidenceFactory, OwnershipHistoryProvenanceEvidenceError } = require("../src/services/ownership-history-provenance-evidence-factory.js");

const catalog = { territoryKeys: [{ row: 1, col: 1 }], structures: [{ structureId: "fort-1", footprint: [{ row: 1, col: 1 }] }] };
function territory() { return { ownershipRecordId: "ownership-1", serverId: "server-366", seasonId: "season-1", territoryRef: { type: "normal_map_cell", row: 1, col: 1 }, ownerUnionId: "union-1", ownershipState: "owned", reviewState: "confirmed", effectiveAt: "2026-08-01T00:00:00Z", sourceType: "manual_entry", evidenceIds: [], actorId: "actor-1", reviewerId: "reviewer-1", reviewedAt: "2026-08-01T00:10:00Z", supersededBy: null }; }
function persisted(ownership = {}) { return { schemaVersion: 1, seasonId: "season-1", baseMapId: "season1-map", savedAt: "2026-08-01T00:00:00.000Z", servers: [{ id: "server-366", ownership }] }; }
function factory(evaluatorOverride) { return createOwnershipHistoryProvenanceEvidenceFactory({ createCompletenessEvaluator: evaluatorOverride || ((options) => createOwnershipHistoryCompletenessEvaluator({ ...options, ownershipHistoryResolver: createOwnershipHistoryResolver(options), ownershipProjectionComparator: createOwnershipProjectionComparator() })) }); }
function input(overrides = {}) { return { seasonId: "season-1", serverId: "server-366", baseMapId: "season1-map", territoryRecords: [territory()], structureRecords: [], targetCatalog: catalog, persistedProjection: persisted({ "1-1": "union-1" }), sourceKind: "existing_generation", sourceDocumentIds: ["strategic-season-1"], ...overrides }; }
function expectError(fn, code) { assert.throws(fn, (error) => error instanceof OwnershipHistoryProvenanceEvidenceError && error.code === code); }
const tests = [];
function test(name, fn) { tests.push({ name, fn }); }
test("derives evaluator fields and sorts diagnostics and sources", () => { const output = factory().createEvidence(input({ sourceDocumentIds: ["z", "a"], persistedProjection: persisted({}) })); assert.strictEqual(output.territoryCoverage.classification, "complete"); assert.strictEqual(output.structureCoverage.classification, "structurally_empty"); assert.strictEqual(output.projectionRelationship.status, "reconciliation_required"); assert.deepStrictEqual(output.sourceDocumentIds, ["a", "z"]); assert.ok(!Object.prototype.hasOwnProperty.call(output, "trust")); });
test("validates first-run and preserves unsafe existing or legacy results", () => { const first = factory().createEvidence(input({ territoryRecords: [], sourceKind: "first_run", sourceDocumentIds: [], persistedProjection: persisted({}) })); assert.strictEqual(first.sourceKind, "first_run"); expectError(() => factory().createEvidence(input({ sourceKind: "first_run", sourceDocumentIds: [] })), "invalid_input"); const legacy = factory().createEvidence(input({ sourceKind: "legacy_migration", sourceDocumentIds: ["legacy-data", "legacy-server"], territoryRecords: [] })); assert.strictEqual(legacy.territoryCoverage.classification, "projection_only"); assert.strictEqual(legacy.projectionRelationship.classification, "projection_only"); });
test("rejects forged derived fields, bad sources, and duplicate references", () => { expectError(() => factory().createEvidence(input({ territoryCoverage: { classification: "complete" } })), "invalid_input"); expectError(() => factory().createEvidence(input({ sourceKind: "first_run", sourceDocumentIds: ["source"] })), "invalid_input"); expectError(() => factory().createEvidence(input({ sourceKind: "existing_generation", sourceDocumentIds: [] })), "invalid_input"); expectError(() => factory().createEvidence(input({ sourceDocumentIds: ["same", "same"] })), "invalid_input"); });
test("keeps scope and inputs isolated and output deterministic", () => { const first = input({ sourceDocumentIds: ["b", "a"] }); const second = { ...input({ sourceDocumentIds: ["a", "b"] }), targetCatalog: { structures: [{ footprint: [{ col: 1, row: 1 }], structureId: "fort-1" }], territoryKeys: [{ col: 1, row: 1 }] }, territoryRecords: first.territoryRecords.slice().reverse() }; const before = JSON.stringify(first); assert.deepStrictEqual(factory().createEvidence(first), factory().createEvidence(second)); assert.strictEqual(JSON.stringify(first), before); expectError(() => factory().createEvidence(input({ serverId: "server-367" })), "invalid_evaluator_result"); });
test("rejects invalid evaluator output and has no host integration", () => { expectError(() => factory(() => ({ evaluate: () => ({ seasonId: "season-1", serverId: "server-366", territoryCoverage: { classification: "forged", targetKeys: [] }, structureCoverage: { classification: "structurally_empty", targetKeys: [] }, projectionRelationship: { classification: "structurally_empty", targetKeys: [], status: "matching", differences: [] }, safetyDiagnostics: [] }) })).createEvidence(input()), "invalid_evaluator_result"); const source = fs.readFileSync(path.join(__dirname, "..", "src", "services", "ownership-history-provenance-evidence-factory.js"), "utf8"); const sandbox = { globalThis: {} }; vm.createContext(sandbox); vm.runInContext(source, sandbox); assert.strictEqual(typeof sandbox.globalThis.createOwnershipHistoryProvenanceEvidenceFactory, "function"); assert.ok(!/persistence|startup|audit|electron|ipcRenderer|ipcMain|fetch|score|fs|clock|repair/.test(source)); });
let passed = 0; tests.forEach(({ name, fn }) => { fn(); passed += 1; console.log(`PASS ${name}`); }); console.log(`${passed} provenance evidence scenarios passed`);