const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { createOwnershipHistoryResolver } = require("../src/services/ownership-history-resolver.js");
const { createOwnershipProjectionComparator } = require("../src/services/ownership-projection-comparator.js");
const { createOwnershipHistoryCompletenessEvaluator } = require("../src/services/ownership-history-completeness-evaluator.js");

const catalog = { territoryKeys: [{ row: 1, col: 1 }, { row: 1, col: 2 }], structures: [{ structureId: "fort-1", footprint: [{ row: 1, col: 1 }] }] };
function territory(overrides = {}) { return { ownershipRecordId: "ownership-1", serverId: "server-366", seasonId: "season-1", territoryRef: { type: "normal_map_cell", row: 1, col: 1 }, ownerUnionId: "union-1", ownershipState: "owned", reviewState: "confirmed", effectiveAt: "2026-08-01T00:00:00Z", sourceType: "manual_entry", evidenceIds: [], actorId: "actor-1", reviewerId: "reviewer-1", reviewedAt: "2026-08-01T00:10:00Z", supersededBy: null, ...overrides }; }
function structure(overrides = {}) { return { structureOwnershipId: "structure-1", serverId: "server-366", seasonId: "season-1", structureId: "fort-1", ownerUnionId: "union-1", ownershipState: "owned", reviewState: "confirmed", effectiveAt: "2026-08-01T00:00:00Z", sourceType: "manual_entry", evidenceIds: [], actorId: "actor-1", reviewerId: "reviewer-1", reviewedAt: "2026-08-01T00:10:00Z", supersededBy: null, ...overrides }; }
function persisted(ownership = {}) { return { schemaVersion: 1, seasonId: "season-1", baseMapId: "season1-map", savedAt: "2026-08-01T00:00:00.000Z", servers: [{ id: "server-366", ownership }] }; }
function evaluator(target = catalog) { return createOwnershipHistoryCompletenessEvaluator({ targetCatalog: target, ownershipHistoryResolver: createOwnershipHistoryResolver({ targetCatalog: target }), ownershipProjectionComparator: createOwnershipProjectionComparator() }); }
function input(overrides = {}) { return { seasonId: "season-1", serverId: "server-366", territoryRecords: [territory(), territory({ ownershipRecordId: "ownership-2", territoryRef: { type: "normal_map_cell", row: 1, col: 2 } })], structureRecords: [structure()], persistedProjection: persisted({ "1-1": "union-1", "1-2": "union-1" }), ...overrides }; }
function test(name, fn) { try { fn(); console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}`); throw error; } }

test("complete territory and structure coverage is separate", () => { const output = evaluator().evaluate(input()); assert.strictEqual(output.territoryCoverage.classification, "complete"); assert.strictEqual(output.structureCoverage.classification, "complete"); assert.strictEqual(output.projectionRelationship.classification, "complete"); });
test("partial and structurally empty coverage are distinguished", () => { const partial = evaluator().evaluate(input({ territoryRecords: [territory()], structureRecords: [] })); assert.strictEqual(partial.territoryCoverage.classification, "partial"); assert.strictEqual(partial.structureCoverage.classification, "structurally_empty"); const empty = evaluator().evaluate({ ...input(), territoryRecords: [], structureRecords: [], persistedProjection: persisted({}) }); assert.strictEqual(empty.territoryCoverage.classification, "structurally_empty"); assert.strictEqual(empty.projectionRelationship.classification, "structurally_empty"); });
test("projection-only is safe and does not claim completeness", () => { const output = evaluator().evaluate({ ...input(), territoryRecords: [], structureRecords: [], persistedProjection: persisted({ "1-1": "union-1" }) }); assert.strictEqual(output.projectionRelationship.classification, "projection_only"); assert.strictEqual(output.territoryCoverage.classification, "projection_only"); });
test("uncertainty, malformed, contradiction, and supersession are classified", () => { const bounded = territory({ eventAt: { precision: "bounded", earliestAt: "2026-08-01T00:00:00Z", latestAt: "2026-08-02T00:00:00Z" } }); delete bounded.effectiveAt; assert.strictEqual(evaluator().evaluate(input({ territoryRecords: [bounded, territory({ ownershipRecordId: "ownership-2", territoryRef: { type: "normal_map_cell", row: 1, col: 2 } })] })).territoryCoverage.classification, "uncertain"); const cycle = [territory({ ownershipRecordId: "a", reviewState: "superseded", supersededBy: "b" }), territory({ ownershipRecordId: "b", reviewState: "superseded", supersededBy: "a" })]; assert.strictEqual(evaluator().evaluate(input({ territoryRecords: cycle })).territoryCoverage.classification, "malformed"); const conflict = [territory(), territory({ ownershipRecordId: "b" })]; assert.strictEqual(evaluator().evaluate(input({ territoryRecords: conflict })).territoryCoverage.classification, "contradictory"); const old = territory({ ownershipRecordId: "old", reviewState: "superseded", supersededBy: "new" }); const next = territory({ ownershipRecordId: "new" }); const coverage = territory({ ownershipRecordId: "coverage", territoryRef: { type: "normal_map_cell", row: 1, col: 2 } }); assert.strictEqual(evaluator().evaluate(input({ territoryRecords: [old, next, coverage] })).territoryCoverage.classification, "complete"); });
test("projection relationship remains partial when coverage is incomplete and structure disagreement is diagnostic", () => { const output = evaluator().evaluate(input({ territoryRecords: [territory()], structureRecords: [structure({ ownerUnionId: "union-other" })], persistedProjection: persisted({ "1-1": "union-1" }) })); assert.strictEqual(output.territoryCoverage.classification, "partial"); assert.strictEqual(output.projectionRelationship.classification, "partial"); assert.ok(output.safetyDiagnostics.some((entry) => entry.code === "structure_footprint_disagreement")); });
test("scope isolation, permutation equality, and immutability", () => { const first = input(); const second = { ...input(), territoryRecords: first.territoryRecords.slice().reverse(), structureRecords: first.structureRecords.slice().reverse() }; const before = JSON.stringify(first); assert.deepStrictEqual(evaluator().evaluate(first), evaluator().evaluate(second)); assert.strictEqual(JSON.stringify(first), before); const otherProjection = { ...persisted({}), servers: [{ id: "server-367", ownership: {} }] }; const other = evaluator().evaluate(input({ serverId: "server-367", persistedProjection: otherProjection })); assert.strictEqual(other.territoryCoverage.classification, "partial"); });
test("supports browser globals and no host integration", () => { const source = fs.readFileSync(path.join(__dirname, "..", "src", "services", "ownership-history-completeness-evaluator.js"), "utf8"); const sandbox = { globalThis: {} }; vm.createContext(sandbox); vm.runInContext(source, sandbox); assert.strictEqual(typeof sandbox.globalThis.createOwnershipHistoryCompletenessEvaluator, "function"); assert.ok(!/serverState|persistence|generation|audit|electron|document|fetch|score|fs|clock/.test(source)); });

console.log("7 ownership history completeness scenarios passed");